In [18]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv("DateFruit_Dataset.csv")

In [20]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [21]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [22]:
df.shape

(898, 35)

In [23]:
X=df.drop("Class", axis=1)
y=df["Class"]

In [24]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [25]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [26]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)

In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(
    X,y, test_size=0.2, random_state=42
)

In [30]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

ANN

In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [33]:
X_train_tensor=torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor=torch.tensor(y_train, dtype=torch.long)

X_test_tensor=torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor=torch.tensor(y_test, dtype=torch.long)

In [34]:
train_dataset=TensorDataset(X_train_tensor, y_train_tensor)
test_dataset=TensorDataset(X_test_tensor, y_test_tensor)

In [36]:
train_loader=DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader=DataLoader(test_dataset, batch_size=32)

In [48]:
#BUilding Model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model=nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64,64),
            nn.ReLU(),
            nn.Linear(64,7),
        )

    def forward(self,x):
        return self.model(x)

In [49]:
model=ANN()

#Loss & optim
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [50]:
#Trainign the NN

epochs=100
for epoch in range(epochs):
    model.train()

    running_loss=0.00
    for xb,yb in train_loader:

        optimizer.zero_grad()
        
        outputs=model(xb)
        loss=criteria(outputs,yb)
        loss.backward()
        optimizer.step() #Weight of params update

        running_loss+=loss

    train_loss=running_loss/len(train_loader)

    print(f"epoch={epoch+1}/{epochs}, loss={train_loss}")

epoch=1/100, loss=1.7013671398162842
epoch=2/100, loss=1.102849006652832
epoch=3/100, loss=0.6898956894874573
epoch=4/100, loss=0.5310420393943787
epoch=5/100, loss=0.44618508219718933
epoch=6/100, loss=0.39316004514694214
epoch=7/100, loss=0.349885493516922
epoch=8/100, loss=0.3098607361316681
epoch=9/100, loss=0.2803134620189667
epoch=10/100, loss=0.2621499300003052
epoch=11/100, loss=0.2409268468618393
epoch=12/100, loss=0.22847673296928406
epoch=13/100, loss=0.22401030361652374
epoch=14/100, loss=0.202618807554245
epoch=15/100, loss=0.1921931505203247
epoch=16/100, loss=0.18419700860977173
epoch=17/100, loss=0.1838490217924118
epoch=18/100, loss=0.17223425209522247
epoch=19/100, loss=0.17117418348789215
epoch=20/100, loss=0.16881290078163147
epoch=21/100, loss=0.1655607372522354
epoch=22/100, loss=0.15045492351055145
epoch=23/100, loss=0.14479362964630127
epoch=24/100, loss=0.14261707663536072
epoch=25/100, loss=0.144182488322258
epoch=26/100, loss=0.14717432856559753
epoch=27/100, loss=0.1337622106075287
epoch=28/100, loss=0.14321592450141907
epoch=29/100, loss=0.132032111287117
epoch=30/100, loss=0.12046239525079727
epoch=31/100, loss=0.11577054858207703
epoch=32/100, loss=0.11317078024148941
epoch=33/100, loss=0.11544356495141983
epoch=34/100, loss=0.11696135252714157
epoch=35/100, loss=0.11596054583787918
epoch=36/100, loss=0.11125408113002777
epoch=37/100, loss=0.10658092051744461
epoch=38/100, loss=0.10280700027942657
epoch=39/100, loss=0.11549796164035797
epoch=40/100, loss=0.09674658626317978
epoch=41/100, loss=0.09498994052410126
epoch=42/100, loss=0.08890083432197571
epoch=43/100, loss=0.09020133316516876
epoch=44/100, loss=0.09632840007543564
epoch=45/100, loss=0.09379512071609497
epoch=46/100, loss=0.08625516295433044
epoch=47/100, loss=0.08233044296503067
epoch=48/100, loss=0.08081148564815521
epoch=49/100, loss=0.07674247771501541
epoch=50/100, loss=0.07755192369222641
epoch=51/100, loss=0.08336786925792694
epoch=52/100, loss=0.0864788219332695
epoch=53/100, loss=0.07873832434415817
epoch=54/100, loss=0.07161881774663925
epoch=55/100, loss=0.07091622799634933
epoch=56/100, loss=0.07332658767700195
epoch=57/100, loss=0.07094517350196838
epoch=58/100, loss=0.06849619746208191
epoch=59/100, loss=0.06938251107931137
epoch=60/100, loss=0.06603401899337769
epoch=61/100, loss=0.06210414320230484
epoch=62/100, loss=0.05964122712612152
epoch=63/100, loss=0.058935657143592834
epoch=64/100, loss=0.059926580637693405
epoch=65/100, loss=0.05706366151571274
epoch=66/100, loss=0.05441929027438164
epoch=67/100, loss=0.05523724481463432
epoch=68/100, loss=0.059656981378793716
epoch=69/100, loss=0.05640037730336189
epoch=70/100, loss=0.052925411611795425
epoch=71/100, loss=0.05193295702338219
epoch=72/100, loss=0.04890885949134827
epoch=73/100, loss=0.04890294745564461
epoch=74/100, loss=0.045694392174482346
epoch=75/100, loss=0.04343665763735771
epoch=76/100, loss=0.046628065407276154
epoch=77/100, loss=0.04396411031484604
epoch=78/100, loss=0.04988851398229599
epoch=79/100, loss=0.04756036028265953
epoch=80/100, loss=0.042294371873140335
epoch=81/100, loss=0.038228049874305725
epoch=82/100, loss=0.04042608290910721
epoch=83/100, loss=0.03937157988548279
epoch=84/100, loss=0.05184515193104744
epoch=85/100, loss=0.0403614342212677
epoch=86/100, loss=0.03749891370534897
epoch=87/100, loss=0.03461523726582527
epoch=88/100, loss=0.0341699942946434
epoch=89/100, loss=0.03951084241271019
epoch=90/100, loss=0.03494798392057419
epoch=91/100, loss=0.03198114410042763
epoch=92/100, loss=0.03852233290672302
epoch=93/100, loss=0.035422906279563904
epoch=94/100, loss=0.03150136023759842
epoch=95/100, loss=0.032841481268405914
epoch=96/100, loss=0.031098270788788795
epoch=97/100, loss=0.030724115669727325
epoch=98/100, loss=0.027396883815526962
epoch=99/100, loss=0.02881302498281002
epoch=100/100, loss=0.029796382412314415

In [58]:
#Evaluation

model.eval()
total=0
correct=0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs=model(xb) #[0.2,0.4,1.3,-0.5,....]
        _, predicted=torch.max(outputs,1)
    
        correct+=(predicted==yb).sum().item()
        total+=yb.size(0)

print("total vals:", total)
print("correct vals:", correct)

print("accuracy:", correct/total*100)

total vals: 180
correct vals: 173
accuracy: 96.11111111111111

In [59]:
y_test.shape

(180,)